data:
  root: ./data/transMVS
  category: transparent
  img_wh: [960, 640]
  nviews: 6
  depth_min: 0.1
  depth_max: 100000

train:
  robust: True

fpn:
  levels: [0, 1, 2, 3] # in 2**x
  base_channels: 8
  gn: False
  dcn: False
